Subscriptions
fonbeauty/developer_portal pull request #16
Opened 2023-03-21 12:09 UTC by OvsyannikovIgor

2023-03-22 11:47 UTC, fonbeauty requested changes

2023-03-22 11:47 UTC, fonbeauty commented on model/components/profile.py
> +    # _PRODUCTS_PAGE = 'a[href="/profile/00000009-0001-0000-9007-000000000002/products"]'
Эти закомменченные строки нужны?

2023-03-22 11:47 UTC, fonbeauty commented on model/components/product.py
> +    # _PRODUCT = 'a[href="https://10.36.133.96:2100/profile/00000009-0001-0000-9007-000000000002/product' \
Эти закомменченные строки нужны?

2023-03-22 11:47 UTC, fonbeauty commented on model/components/product.py
> +    # def go_to_product(self) -> None:
Нужен закомменченный код?

2023-03-22 11:47 UTC, fonbeauty commented on model/components/product.py
> +    # def test_subscribe_click(self) -> None:
Нужен закомменченный код?

2023-03-22 11:47 UTC, fonbeauty commented on model/components/profile.py
> +    # def go_to_product_page(self) -> None:
Код закомменченный нужен?

2023-03-22 11:47 UTC, fonbeauty commented on model/components/subscription.py
> +    # def next_page_click(self):
Код закомменченный нужен?

2023-03-22 11:47 UTC, fonbeauty commented on tests/test_applications.py
> +    app.main_page.open_catalog()
Я правильно понял, что сначала приложение создается и подписывается и только потом происходит отписка?
Если да, то создание и подписку приложения надо вынести в фикстуру

2023-03-27 20:15 UTC, fonbeauty requested changes

2023-03-27 20:15 UTC, fonbeauty commented on model/components/catalog.py
>      _PRODUCT = '[href="/product/prodCode002st9007"]'
Стендозависимый локатор?

2023-03-27 20:15 UTC, fonbeauty commented on tests/test_applications.py
> +def subs_and_select_app(app: ApplicationManager) -> str:
давай полностью без сокращений напишем

2023-03-27 20:15 UTC, fonbeauty commented on tests/test_applications.py
> +    with allure.step('Проверка отозванного сертификата'):
Добавь пустую строку перед  with allure.step('Проверка отозванного сертификата'):

2023-03-27 20:15 UTC, fonbeauty commented on tests/test_applications.py
> +    with allure.step('Проверка оформленной подписки'):
Добавь пустую строку перед with allure.step('Проверка оформленной подписки'):

2023-03-27 20:15 UTC, fonbeauty commented on tests/test_applications.py
> +    with allure.step('Проверки созданного приложения и оформленной подписки'):
Добавь пустую строку перед with allure.step('Проверки созданного приложения и оформленной подписки'):

2023-03-27 20:15 UTC, fonbeauty commented on model/components/profile.py
> +    def open_create_subs_application(self, app_href) -> None:
Какой смысл закладывался в название этого метода?

2023-03-28 07:21 UTC, OvsyannikovIgor commented on model/components/catalog.py
>      _PRODUCT = '[href="/product/prodCode002st9007"]'
Да, такого продукта нет на другом стенде. Так как не на каждый продукт можно оформить подписку сделано так. Есть идея сделать цикл, где рандомно выбирается продукт до тех пор пока не попадётся активная кнопка оформить подписку.

2023-03-28 20:15 UTC, fonbeauty approved these changes

2023-03-29 07:07 UTC, merged